### ISSUE TITLE
大家都发布一个包

### ISSUE THREAD

**Issue by zhufengzhufeng** [zhufengpeixun1/homework_node5#43]

**Comment by raxxarr** [comment]
<img width="311" alt="2016-06-19 12 06 13" src="https://cloud.githubusercontent.com/assets/7265362/16175085/5dbd1d66-3616-11e6-94a2-bc49b2759d35.png">
<img width="301" alt="2016-06-19 12 07 27" src="https://cloud.githubusercontent.com/assets/7265362/16175088/6c9a59de-3616-11e6-887e-809c08cec677.png">

**Comment by jessjava** [comment]
i'm coming
![Uploading npmpublish.png…]()

**Comment by ghost** [comment]
![Uploading 11111111111111.png…]()

**Comment by lishu1994** [comment]
<img width="382" alt="img" src="https://cloud.githubusercontent.com/assets/18398079/16175105/bd00aac2-3616-11e6-9a04-b632fc329439.png">

**Comment by Jing-wj** [comment]
![Uploading npmPublish.png…]()

**Comment by skybjf** [comment]
![npm](https://cloud.githubusercontent.com/assets/6185151/16175116/edcc1682-3616-11e6-885f-597a1a1c75b8.png)

**Comment by pengfei6** [comment]
![Uploading QQ截图20160619121058.jpg…]()
